TASK_TYPE: inference_t2v_deepspeed
ENABLE: False
use_ema: False
num_workers: 16


max_frames: 16
sample_fps: 3
resolution: [256,256]

## deoning batch size
batch_size: 16

decoder_bs: 16

# inference_scale: 8
inference_seed: 42

model_name: "DEMO"



infer_dataset: {
    'type': 'VisualDatasetRepeat',
    'csv_path': 'prompts/test_prompt.csv',
    'repeat_times': 20,
}



embedder: {
    'type': 'FrozenOpenCLIPEmbedder',
    'layer': 'penultimate',
    # 'vit_resolution': [224, 224],
    'pretrained': '/lab/shiyh_lab/12250073/ENHANCE_MOTION/models/modelscope/open_clip_pytorch_model.bin',
    'freeze': True
}

motion_encoder: {
    'type': 'MotionEncoder',
    'layer': 'penultimate',
    # 'vit_resolution': [224, 224],
    # 'pretrained': 'models/DEMO/temporal_embedder.pth',
    'pretrained': "/lab/shiyh_lab/12250073/ENHANCE_MOTION/non_ema_00312000_temporal_embedder.pth",
    'freeze': True,
    'from_incomplete': True,
}


Pretrain: {
    'type': load_model,
    'from_modelscope': False,
    'inference': True,
    'resume_checkpoint': '/lab/shiyh_lab/12250073/ENHANCE_MOTION/non_ema_00312000.pth',
}




UNet: {
    'type': 'UNetSD_T2V_DEMO',
    'in_dim': 4,
    'y_dim': 1024,
    'upper_len': 128,
    'context_dim': 1024,
    'out_dim': 4,
    'dim_mult': [1, 2, 4, 4],
    'num_heads': 8,
    'default_fps': 8,
    'head_dim': 64,
    'num_res_blocks': 2,
    'dropout': 0.1,
    'misc_dropout': 0.4,
    'temporal_attention': True,
    'temporal_attn_times': 1,
    'use_checkpoint': True,
    'use_fps_condition': False,
    'use_sim_mask': False,
    'text_reweight': True,
}



Diffusion: {
    'type': 'DiffusionDDIM',
    'schedule': 'linear_sd', # cosine
    'schedule_param': {
        'num_timesteps': 1000,
        'init_beta': 0.00085,
        'last_beta': 0.0120,
        'zero_terminal_snr': False,
    },
    'mean_type': 'eps',
    'loss_type': 'mse',
    'var_type': 'fixed_small',
    'rescale_timesteps': False,
    'noise_strength': 0.0
}



guide_scale: 9.0

## vqa encode&decode scale
scale: 8

# Log
log_dir: "inference"




## from config.py
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]
max_words: 1000
# num_workers: 8
prefetch_factor: 1
ddim_timesteps: 50  # official: 250
use_div_loss: False

# Model
scale_factor: 0.18215  
use_fsdp: False 
use_fp16: True
temporal_attention: True



auto_encoder: {
    'type': 'AutoencoderKL',
    'ddconfig': {
        'double_z': True, 
        'z_channels': 4,
        'resolution': 256, 
        'in_channels': 3,
        'out_ch': 3, 
        'ch': 128, 
        'ch_mult': [1, 2, 4, 4],
        'num_res_blocks': 2, 
        'attn_resolutions': [], 
        'dropout': 0.0,
        'video_kernel_size': [3, 1, 1]
    },
    'embed_dim': 4,
    # 'pretrained': 'models/v2-1_512-ema-pruned.ckpt'
    'pretrained': '/lab/shiyh_lab/12250073/ENHANCE_MOTION/models/modelscope/VQGAN_autoencoder.pth'
}

negative_prompt: 'Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms'

# training and optimizer
ema_decay: 0.9999

weight_decay: 0.0
alpha: 0.7

# scheduler
warmup_steps: 10
decay_mode: 'cosine'


deepspeed_config: "ds_configs/ds_config_inference.json"